spring.application.name=product-ms

### Permite al microservicio y sus instancias ejecutarse en un puerto disponible
# al momento de la ejecución, evitando conflictos de puertos.
# Esencial para una arquitectura de microservicios.
server.port=0

### Configuración de conexión a Kafka
## Lista de los Brokers de Kafka para la comunicación entre el microservicio y el clúster de Kafka.
## Siempre especificar por lo menos 2 brokers para asegurar alta disponibilidad y tolerancia a fallos.
## No hace falta listar todos los brokers, pero es recomendable incluir varios.
spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096


### Configuracion que define los serializadores para las claves y valores de los mensajes enviados a Kafka.
## En este caso, se utiliza StringSerializer para las claves y JsonSerializer para los valores.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

### KAFKA ACKNOWLEDGEMENT
## Configuración de ACKs para garantizar la entrega de mensajes a Kafka.
## "all" = todos los brokers han replicados el mensaje.
## 1 = el líder del topic ha recibido el mensaje (más rápido pero menos seguro).
## 0 = no se espera ningún ACK (más rápido pero menos seguro).
spring.kafka.producer.acks=all


### KAFKA MESSAGE RETRIES
## Configuración de reintentos para el envío de mensajes a Kafka en caso de fallos
## Número de reintentos antes de considerar el envío como fallido.
## Valor por defecto es 2147483647, pero se puede ajustar según las necesidades de la aplicación.
## NOTA: Pasada la cantidad de reintentos, si no se recibe el ack se lanza una excepción.
spring.kafka.producer.retries=10

## TIEMPO DE ESPERA ENTRE REINTENTOS
## Configuración del tiempo de espera entre reintentos para el envío de mensajes a Kafka.
## Valor en milisegundos. Por ejemplo, 1000 ms = 1 segundo
spring.kafka.producer.retry-backoff-ms=1000

### CONFIGURACIÓN DE TIMEOUTS
## Configuración de tiempos de espera para el envío de mensajes a Kafka.
## delivery.timeout.ms: Tiempo máximo que el productor esperará para que un mensaje sea entregado a Kafka antes de considerarlo fallido. Valor en milisegundos.
spring.kafka.producer.properties.delivery.timeout.ms=35000

## request.timeout.ms: Tiempo máximo que el productor esperará para recibir un ACK de Kafka antes de considerar el envío como fallido. Valor en milisegundos.
spring.kafka.producer.properties.request.timeout.ms=30000

## linger.ms: Tiempo que el productor esperará para acumular mensajes antes de enviarlos a Kafka. Valor en milisegundos. Un valor de 0 significa que los mensajes se enviarán inmediatamente sin esperar a acumular más mensajes.
spring.kafka.producer.properties.linger.ms=0
####################

### IMPORTANTE DE KAFKA => IDEMPOTENCIA
## Configuración para garantizar la idempotencia en el envío de mensajes a Kafka.
## idempotence: Habilita la idempotencia para asegurar que los mensajes se guarden exactamente una vez, incluso en caso de reintentos debido a fallos.
## Esto evita la duplicación de mensajes en Kafka, lo cual es crucial para mantener la integridad de los datos en una arquitectura de microservicios.
## Por defecto la idempotencia está habilitada en Kafka, pero es recomendable asegurarse de que esté configurada correctamente.
spring.kafka.producer.properties.enable.idempotence=true


### KAFKA TOPICS ###################
kafka.topics.product.product-created=product-created-event-topic


### POSTGRESQL CONFIGURATION
# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kafka_project_db
spring.datasource.username=gabriel_admin
spring.datasource.password=gabriel_12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# ===============================
# Connection Pool (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# Timezone (recomendado)
# ===============================
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

################################################################################
### URLS DE LAS APIS EXTERNAS
## URL BASE DE LA POKEAPI
apis.externas.pokeapi.base.url=https://pokeapi.co/api/v2


