spring.application.name=email-notification-msv

server.port=0

# CONFIGURACIONES DE KAFKA
# Lista de brokers de Kafka a los que se conectara el consumidor
spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096

# Configuracion de deserializadores para las claves y valores de los mensajes
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# Configuracion del grupo de consumidores al que pertenece este consumidor (consumer-group)
spring.kafka.consumer.group-id=email-notification-group

# Configuracion para confiar en todos los paquetes al deserializar objetos JSON
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# TOPICS consumidos por este microservicio
kafka.topics.product.product-created=product-created-event-topic

# TOPICS de dead-letter para manejar mensajes que no se pudieron procesar correctamente
kafka.topics.product.product-created.dlt=product-created-event-topic.DLT

################################################################################
### URLS DE LAS APIS EXTERNAS
## URL BASE DE LA POKEAPI
apis.externas.pokeapi.base.url=https://pokeapi.co/api/v2


##########################################################################################################
### CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL (USADA PARA GUARDAR IDEMPOTENCIA DE LOS MENSAJES PROCESADOS)
### POSTGRESQL CONFIGURATION
# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/kafka_project_db
spring.datasource.username=gabriel_admin
spring.datasource.password=gabriel_12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
# ===============================
# Connection Pool (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000


